<?php

/**
 * @file
 * Contains citrus_catdaycare.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function citrus_catdaycare_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the citrus_catdaycare module.
    case 'help.page.citrus_catdaycare':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Citrus Cat Daycare') . '</p>';
      return $output;

    default:
  }
}
